trigger:
  branches:
    include:
    - main
    - master
    - develop

parameters:
  - name: baseImageNameShort
    displayName: "Select base image:"
    type: string
    default: "distroless-base-debian11"
    values:
    - distroless-base-debian11
    - distroless-static-debian11
    - distroless-base-debian10
    - distroless-static-debian10
  - name: correttoVersionMajor
    displayName: "Select Corretto major version:"
    type: number
    default: 8
    values:
    - 8
    - 11
    - 17
  - name: tomcatVersionMajor
    displayName: "Select Tomcat major version:"
    type: number
    default: 10
    values:
    - 8
    - 9
    - 10
  - name: buildWithTomcatNative
    displayName: "Build with Tomcat Native Library?"
    type: string
    default: "No"
    values:
      - "No"
      - "Yes"

variables:
  # ACR where to push new image
  - name: acrName
    value: "cloudladderacr.azurecr.io"
  # Global variable to be used in different tasks/jobs/stages
  - name: baseImageName
    value: "willBeSetByBashTask"
  # Global variable to be used in different tasks/jobs/stages
  - name: tomcatVersionFull
    value: "willBeSetByBashTask"
  # Global variable to be used in different tasks/jobs/stages
  - name: imageName
    value: "willBeSetByBashTask"
  # Global variable to be used in different tasks/jobs/stages
  - name: imageTag
    value: "willBeSetByBashTask"
  # Dokerfile argument passed to "docker build"
  - name: dockerfilePath
    value: "willBeSetByBashTask"
  - name: trivyVersion
    value: 'latest'  

# TODO:
# Fix TOMCAT_V_VERSION variable filtering for "tomcat-10"
# Support "native" or "no native" Dockerfiles from single pipeline (or don't - need to decide)

jobs:
- job:
  displayName: "Build Tomcat image based on distroless Debian-based image (based on gcr.io/distroless) with Amazon Corretto OpenJDK"
  timeoutInMinutes: 10
  pool: 
    vmImage: ubuntu-latest
  steps:
    - script: |
        sudo apt-get install rpm
        wget https://github.com/aquasecurity/trivy/releases/download/v$(trivyVersion)/trivy_$(trivyVersion)_Linux-64bit.deb
        sudo dpkg -i trivy_$(trivyVersion)_Linux-64bit.deb
        trivy -v
      displayName: 'Download and install Trivy'

    - task: Bash@3
      continueOnError: false
      displayName: "Download Tomcat and prepare variables"
      inputs:
        targetType: 'inline'
        script: |
          TOMCAT_MAJOR=${{ parameters.tomcatVersionMajor }}
          TOMCAT_VERSION_FULL=$(curl -sk https://dlcdn.apache.org/tomcat/tomcat-${TOMCAT_MAJOR}/ | grep -m 1 ">v${TOMCAT_MAJOR}" | sed "s/.*>v${TOMCAT_MAJOR}/${TOMCAT_MAJOR}/" | sed 's/\/<.*//')
          DATE="$(date +%Y%m%d)"
          BASE_IMAGE_NAME="${{ parameters.baseImageNameShort }}-corretto${{ parameters.correttoVersionMajor }}"
          IMAGE_TAG="${TOMCAT_VERSION_FULL}-${DATE}-$(Build.BuildId)"
          WITH_NATIVE="${{ parameters.buildWithTomcatNative }}"
          # Build without Tomcat Native Library
          if [ "$WITH_NATIVE" = "No" ]
          then
            IMAGE_NAME="${BASE_IMAGE_NAME}-tomcat${{ parameters.tomcatVersionMajor }}"
            DOCKER_FILE_PATH="dockerfiles/distroless-debian-tomcat"
            echo "##vso[build.updatebuildnumber]${IMAGE_TAG}"
          # Build with Tomcat Native Library
          else
            IMAGE_NAME="${BASE_IMAGE_NAME}-tomcat${{ parameters.tomcatVersionMajor }}-native"
            DOCKER_FILE_PATH="dockerfiles/distroless-debian-tomcat-native"
            BUILD_NUMBER="${TOMCAT_VERSION_FULL}-native-${DATE}-$(Build.BuildId)"
            echo "##vso[build.updatebuildnumber]${BUILD_NUMBER}"
          fi
          echo "##vso[task.setvariable variable=tomcatVersionFull]${TOMCAT_VERSION_FULL}"
          echo "##vso[task.setvariable variable=baseImageName]${BASE_IMAGE_NAME}"
          echo "##vso[task.setvariable variable=imageName]${IMAGE_NAME}"
          echo "##vso[task.setvariable variable=imageTag]${IMAGE_TAG}"
          echo "##vso[task.setvariable variable=dockerfilePath]${DOCKER_FILE_PATH}"
          echo "${TOMCAT_VERSION_FULL}"
          echo "${BASE_IMAGE_NAME}"
          echo "${IMAGE_NAME}"
          echo "${IMAGE_TAG}"
          echo "${DOCKER_FILE_PATH}"

    - task: Docker@2
      continueOnError: false
      displayName: "Build Docker image"
      inputs:
        command: build
        containerRegistry: CLorg-Sub1-ACR
        repository: $(imageName)
        addPipelineData: true
        Dockerfile: $(dockerfilePath)
        tags: |
          $(imageTag)
          latest
        arguments: |
         --build-arg baseImageName="$(baseImageName)"
         --build-arg baseImageTag="latest"
         --build-arg tomcatVersionMajor="${{ parameters.tomcatVersionMajor }}"
         --build-arg tomcatVersionFull="$(tomcatVersionFull)"
         --build-arg imageName=$(imageName)
         --build-arg imageTag=$(imageTag)

    - task: Docker@2
      displayName: "Pushing image to ACR $(acrName)"
      inputs:
        containerRegistry: "CLorg-Sub1-ACR"
        repository: $(imageName)
        tags: |
          $(imageTag)
          latest
        command: push

    - task: Docker@2
      displayName: "Docker ACR login"
      inputs:
        containerRegistry: 'CLorg-Sub1-ACR'
        command: 'login'

    - task: CmdLine@2
      displayName: "Run trivy scan"
      inputs:
        script: |
          trivy image --exit-code 0 --severity LOW,MEDIUM $(acrName)/$(imageName):$(imageTag)
          trivy image --exit-code 1 --severity HIGH,CRITICAL $(acrName)/$(imageName):$(imageTag)

          trivy image --exit-code 0 --severity LOW,MEDIUM $(acrName)/$(imageName):$(imageTag) > $(Build.ArtifactStagingDirectory)/_buildOutput/$(imageName)-$(imageTag)-medium-low.txt
          trivy image --exit-code 1 --severity HIGH,CRITICAL $(acrName)/$(imageName):$(imageTag) > $(Build.ArtifactStagingDirectory)/_buildOutput/$(imageName)-$(imageTag)-critical-high.txt

          echo SCAN FINISHED

    - task: CopyFiles@2
      inputs:
        contents: '_buildOutput/**'
        targetFolder: $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: ScanReports